/* AUREUM Bot — the built-in help library. No AI, no internet: just questions and answers written from how AUREUM really works.
   Edit this file, then run:  node tools/build-bot.mjs   (it copies the library and engine into backoffice.html)
   Fields:  id · topic · title · q (ways people ask it) · kw (extra search words) · a (the answer) · rel (related ids)
            pages (screens where it is most relevant) · human (also offer a ticket) · pay + store (payment topic: shown differently in app-store builds) */
(function(root){
const E = (id, topic, title, q, kw, a, rel, o) => Object.assign({ id, topic, title, q, kw, a, rel: rel || [] }, o || {});
const STORE = 'Subscriptions are managed from your AUREUM account on the web. This screen shows your subscription status.';
const KB = [

/* ============ GETTING STARTED ============ */
E('what-is-aureum','Getting started','What is AUREUM?',
  ['what is aureum','what does aureum do','what can aureum do','tell me about aureum','what are the parts of aureum'],
  'overview pos back office control panel features software system',
  `AUREUM is a point-of-sale (POS) and back-office system for shops, including businesses with several shops.\n\n- **Back Office** — where the owner or manager sets everything up and reads reports (this screen).\n- **POS Checkout (the till)** — where cashiers sell. Open it with **Open POS Checkout** at the bottom of the left menu.\n- **Control panel** — used only by the AUREUM team.\n\nIt works in a browser on a computer, tablet or phone, can be installed like an app, and keeps working offline.`,
  ['get-started','open-pos','install-app']),
E('get-started','Getting started','How do I get started?',
  ['how do i get started','how do i set up aureum','where do i begin','first steps','setup checklist','how to start using aureum'],
  'begin setup new account first time onboarding checklist',
  `A good order for setting up:\n\n1. **Settings → Business Profile** — business name and currency.\n2. **Settings → Stores** — add your shops (every shop is included in the free trial).\n3. **Settings → Taxes** — tax rate and whether prices include tax.\n4. **Products → Add Product** (or **Import** from Excel) — your items and stock.\n5. **Employees → Add Employee** — each cashier with a 4-digit PIN.\n6. **Settings → Receipts** and **Payment Methods** — how receipts look and which payment buttons show.\n7. **Open POS Checkout**, sign in, and make a test sale.`,
  ['add-store','add-product','add-employee','open-pos'], { pages:['dashboard'] }),
E('open-pos','Getting started','How do I open the till (POS)?',
  ['how do i open the pos','where is the till','open pos checkout','how do cashiers sell','how do i get to the checkout screen','how do my cashiers start selling'],
  'point of sale register open launch cashier screen',
  `Press **Open POS Checkout** at the bottom of the left menu. Cashiers then pick the shop, their name and their PIN to sign in. You can also install the POS as its own app on a tablet or phone (see "Can I install AUREUM as an app?").`,
  ['pos-signin','install-app']),
E('install-app','Getting started','Can I install AUREUM as an app?',
  ['can i install aureum','how do i install the app','add to home screen','install on my phone','install on my computer','is there an app','is there a mobile app'],
  'pwa home screen desktop shortcut application download mobile phone android iphone',
  `Yes. In Chrome or Edge use the **Install** icon in the address bar (or menu → **Install app**). On a phone, open the menu and choose **Add to Home screen**. The Back Office and the POS can be installed separately, so a till can have just the checkout.`,
  ['offline']),
E('offline','Getting started','Does AUREUM work without internet?',
  ['does it work offline','what if the internet goes down','can i sell without internet','no internet','work without wifi','what happens when offline'],
  'offline connection wifi network disconnected sync later',
  `Yes — once the Back Office or POS has been opened with internet at least once, it opens without a connection. The till keeps selling; sales are kept on the device and **sync automatically** when the internet returns. Things that need the internet while offline: signing in for the first time, billing, and adding a paid shop.`,
  ['sync-status','till-offline']),
E('sync-status','Getting started','What does "Synced" mean?',
  ['what does synced mean','sync status','sales not showing on other device','changes not appearing on the till','how long does sync take','is my data saved','the till does not show my changes','new price not showing at the till'],
  'syncing saved cloud update device status sidebar footer price change not updated new price not showing',
  `The status at the bottom of the left menu shows whether your data is saved to your account. **Synced** means everything is up to date. Changes usually reach other devices within a few seconds. If a device was offline it catches up when it reconnects. If it stays on a problem message, check the internet and refresh once; if it continues, send a ticket.`,
  ['refresh-old','sync-problem','offline']),
E('refresh-old','Getting started','The app looks old or a button is missing',
  ['the app looks old','button is missing','i dont see the new feature','how do i update the app','how do i refresh','hard refresh','page not updating'],
  'update new version cache reload ctrl shift r stale outdated',
  `Refresh the page: press **Ctrl+Shift+R** on a computer. On a phone or tablet close the tab (or the installed app) and open it again. New versions arrive the next time the app is opened with internet.`,
  ['sync-status']),
E('who-can-sign-in','Getting started','Who can sign in, and how do staff log in?',
  ['how do staff log in','how do cashiers sign in','do employees need an account','who can use the back office','can my staff access the back office','staff login','who can see the reports'],
  'employee login cashier account owner pin name password access',
  `The **owner** signs in with email and password to the Back Office and the POS. **Staff do not have their own logins**: at the POS a cashier chooses the shop, then their name, then their 4-digit PIN. Create employees in **Employees → Add Employee**. Staff cannot sign in to the Back Office.`,
  ['add-employee','employee-pin','roles']),
E('forgot-password','Getting started','I forgot my password',
  ['i forgot my password','how do i reset my password','cant remember password','reset password','change my password'],
  'forgot reset recover login email link account',
  `On the sign-in screen press **Forgot password**, enter the owner's email and follow the link you receive. To type passwords more easily, use the **eye icon** in the password box to show or hide what you type. If a cashier forgot their **PIN**, change it in **Employees**.`,
  ['cant-sign-in','employee-pin']),
E('roles','Getting started','What roles are there and what can each do?',
  ['what roles are there','what is the difference between cashier and manager','what can a shop manager do','what can an administrator do','employee roles','what is inventory clerk'],
  'cashier shop manager administrator inventory clerk permissions access rights',
  `Roles: **Cashier**, **Shop Manager**, **Inventory Clerk** and **Administrator**.\n\nAt the till, **Shop Manager** and **Administrator** are managers: they can always give discounts, change prices, refund, view Today's Sales, close anyone's shift and open the closed-shifts list. Cashiers and Inventory Clerks are limited by the switches in **Settings → Users & Permissions**.`,
  ['permissions-settings','add-employee']),

/* ============ DASHBOARD ============ */
E('dashboard-overview','Dashboard','What is on the Dashboard?',
  ['what is on the dashboard','what does the dashboard show','how do i see my sales','where can i see how my business is doing','dashboard explained','which cashier sold the most'],
  'home summary overview sales profit charts alerts top performers payment type employee cashier best seller',
  `The **Dashboard** shows, for the shop and dates you choose: **Alerts** (negative and low stock), **Sales Summary** (gross sales vs gross profit, last 7 days), **Sales by Payment Type**, **Sales by Employee** and your top performers. Use the shop and date controls at the top.`,
  ['dashboard-date','dashboard-shop','alerts-low'], { pages:['dashboard'] }),
E('dashboard-date','Dashboard','How do I change the date range?',
  ['how do i change the date','how do i filter by date','how do i see last month','how do i pick a custom date range','date filter','show sales for yesterday'],
  'period range today yesterday week month custom start end apply calendar',
  `Click the date button (it says **Today** by default). Choose **Today, Yesterday, This week, Last week, This month, Last month** or **Custom range** (pick a start and end date, then **Apply**). Most list pages (Receipts, Purchases, Goods Received…) have the same date button.`,
  ['dashboard-shop'], { pages:['dashboard','sales','purchases','goods-received','accounting'] }),
E('dashboard-shop','Dashboard','How do I see just one shop?',
  ['how do i see one shop','how do i switch shops','view a single shop','all shops vs one shop','change shop on dashboard','how do i see another store'],
  'shop store viewing selector dropdown switch compare branch location',
  `Click the shop button (it says **All Shops**) at the top of the Dashboard, or **Viewing** in the left menu, and pick a shop. Sales, stock and reports then show only that shop. Choose **All Shops** to see everything together.`,
  ['dashboard-date','add-store']),
E('alerts-negative','Dashboard','What is a negative stock alert?',
  ['why is my stock negative','what does negative stock mean','stock shows minus','negative stock alert','stock below zero','my stock is in red'],
  'minus below zero oversold red sold more than stock',
  `Negative stock means **more was sold than the system had recorded** (for example, goods arrived but the delivery was not entered yet). AUREUM still lets the sale go through, shows the item in **red** in the product list and till, and lists it under **Negative stock** on the Dashboard.\n\nFix it by recording the delivery in **Goods Received**, or correct the count with a **Stock Adjustment**.`,
  ['grn-receive','stock-adjustment','alerts-view-all']),
E('alerts-low','Dashboard','What is a low stock alert and how do I change the level?',
  ['what is low stock','how do i change the low stock level','low stock threshold','stock alert level','when am i warned about low stock','reorder level','how do i know a product is running out'],
  'threshold safety stock reorder minimum alert 15 default warn running out running out almost finished',
  `An item is **low stock** when its stock reaches its **Low stock alert threshold** (default **15**). Set it per product: **Products → edit a product → Inventory → Low stock alert threshold**. **Safety stock** is the buffer you always want on hand. Low items appear in **Alerts** on the Dashboard and in **Reports → Low Stock**.`,
  ['alerts-view-all','turn-off-low-alerts','product-stock-control']),
E('alerts-view-all','Dashboard','How do I see all the low or negative items?',
  ['how do i see all low stock items','view all alerts','list of items with negative stock','where is the low stock report','show only negative stock'],
  'report list full view all filter everything negative low switch',
  `Under the alert, press **View all**. **View all** under *Negative stock* opens **Reports → Low Stock** showing only negatives; under *Low stock* it shows only low items. On that report you can switch between **Everything**, **Negative stock** and **Low stock**.`,
  ['alerts-negative','alerts-low']),
E('turn-off-low-alerts','Dashboard','How do I turn off low stock alerts?',
  ['turn off low stock alerts','stop low stock warnings','hide low stock on dashboard','disable stock alerts'],
  'notification switch off disable dashboard alerts settings',
  `Go to **Settings → Notifications** and switch off **Low stock alerts**, then **Save changes**. The dashboard stops listing low-stock items (negative stock is always shown, and the Low Stock report still lists everything).`,
  ['notifications-settings']),
E('daily-summary','Dashboard','What is the daily sales summary?',
  ['daily sales summary','yesterdays sales popup','end of day summary','how do i get a daily report','summary of yesterday'],
  'notification popup report email daily morning',
  `Switch on **Daily sales summary** in **Settings → Notifications**. The first time you open the Back Office each day it shows **yesterday's** sales, takings, refunds, net, payment methods and top products. It appears inside the app — AUREUM does not send emails.`,
  ['notifications-settings','email-notifications']),

/* ============ PRODUCTS ============ */
E('add-product','Products','How do I add a product?',
  ['how do i add a product','how do i create an item','add new product','how to add items to the system','how do i add stock items','create a product'],
  'new item create product name price cost save',
  `1. Open **Products** and press **Add Product**.\n2. Enter the **name**, **category**, **price** and **cost**.\n3. Check **Charge tax on this product**, and under **Shops** choose where it is sold and the starting stock.\n4. Optionally add a barcode, description and picture.\n5. Press **Save product**.\n\nThe product code is filled in for you.`,
  ['product-code','product-picture','product-import','product-shops'], { pages:['products'] }),
E('edit-product','Products','How do I edit or delete a product?',
  ['how do i edit a product','how do i change a price','how do i delete a product','remove a product','update product price','change product name'],
  'edit delete remove change update modify price name selected',
  `Open **Products**, click the product, change what you need and press **Save product**. To delete, tick one or more products in the list and press **Delete selected**. Past receipts keep their own copy of each item, so deleting a product never changes old sales.`,
  ['add-product','price-change-till'], { pages:['products'] }),
E('product-code','Products','How do product codes work?',
  ['what is the product code','how are product codes made','can i set my own product code','code already used error','duplicate product code','product has no code'],
  'sku code number unique automatic generated 100001 duplicate',
  `Every product always has a **code**. New codes are automatic (six digits, continuing after the highest code in use, like 100007). You can type your own, but **two products cannot share a code** — you'll be told which product already has it. Leave the box empty and one is generated. Products that had no code get one automatically when the Back Office opens.`,
  ['product-barcode','add-product']),
E('product-barcode','Products','How do barcodes and searching work?',
  ['how do i add a barcode','how do i scan products','barcode scanner','search by barcode at the till','can i use a scanner','find a product quickly'],
  'barcode scan scanner search code find lookup ean upc',
  `Type the barcode into the **Barcode** box when you add or edit a product. At the till, search by **name, code or barcode** in the search box; a barcode scanner that types into the box works as normal typing.`,
  ['product-code','sell-basic']),
E('product-category','Products','How do categories work?',
  ['how do i add a category','how do i create categories','change product category','categories at the till','organise products'],
  'category group type tabs filter pills',
  `Just type a category when you add or edit a product — any word, like *Beverages* or *Household*. New categories appear automatically as filter buttons in the till and the product list. To rename a category, edit the products in it.`,
  ['add-product']),
E('product-tax','Products','How do I make a product tax-free?',
  ['how do i make a product tax free','charge tax on this product','exempt item from tax','zero rated product','no vat on some items','tax free item','products that should not have vat'],
  'tax vat exempt zero charge switch product',
  `Edit the product and switch **off** *Charge tax on this product* under **Tax**. The tax rate (and whether prices include tax) is set in **Settings → Taxes**. For new products, **Apply tax to all new products by default** sets the starting position. Older products are taxed unless you change them.`,
  ['taxes-settings','tax-wrong']),
E('product-picture','Products','How do I add a picture to a product?',
  ['how do i add a product picture','upload a photo for an item','find a picture online','search google images for product','download image for product','product image'],
  'photo image upload picture online google free openverse wikimedia credit',
  `In the product form, under the picture box you can:\n\n- **Click the box** to upload your own photo (it is shrunk automatically).\n- **Find a picture online** — type the product name first, then search free-to-use pictures (Open Food Facts and Wikimedia Commons; **Search more pictures** adds Openverse). Choose one and it is downloaded with its credit.\n- **Search Google Images** — opens Google in a new tab; save a picture and upload it. (AUREUM cannot read Google's results itself.)\n\nPress **Save product** to keep it.`,
  ['add-product']),
E('product-import','Products','How do I import products from Excel or CSV?',
  ['how do i import products','import from excel','upload a spreadsheet of products','bulk add products','import csv','add lots of products at once'],
  'import excel xlsx csv upload spreadsheet bulk template columns preview',
  `1. **Products → Import**, then choose your Excel (.xlsx/.xls) or CSV file.\n2. Check **Match your columns** — only **Product Name** is required; Category, Price, Cost and Stock are optional.\n3. Read the summary and preview (it shows the code each product will get).\n4. Choose which shop receives the stock, then press **Import**.\n\nNeed a layout? Use **Download the Excel template**. Products whose name already exists are skipped, never overwritten.`,
  ['import-problems','add-product'], { pages:['products'] }),
E('import-problems','Products','My import has problems or skipped rows',
  ['import not working','products skipped during import','import says already exist','prices became zero after import','wrong columns in import','import file has no headings'],
  'skipped duplicate zero column heading header unreadable error',
  `- **"Already exist"** — a product with the same name is in AUREUM; it is skipped, not changed.\n- **Prices/stock set to 0** — the file's value couldn't be read (letters, blank cells). Fix the file or the column match.\n- **Wrong column** — on the preview, choose the right column for each field from the lists.\n- **No heading row** — untick *The first row contains column headings*.\n- Rows without a name are skipped.`,
  ['product-import']),
E('product-export','Products','How do I export my products?',
  ['how do i export products','download my product list','save products to excel','print product list','export to pdf'],
  'export csv excel pdf download list print backup',
  `On **Products** press **Export** and choose **CSV, Excel or PDF**. Most lists in AUREUM (receipts, customers, employees, purchases, reports…) have the same Export button.`,
  ['export-data']),
E('product-shops','Products','How do I sell a product in several shops?',
  ['how do i assign products to shops','product in all shops','stock per shop','different stock in each shop','make a product available in another shop','item not in my second shop'],
  'shops store assign available stock per shop branch all shops table',
  `In the product form, the **Shops** section lists your shops. Choose where the item is sold and set the **stock on hand per shop** — stock is always kept **separately for each shop**. "Available in all shops" covers the shops you have at the time you save; if you add a shop later, edit the product to include it.`,
  ['stock-per-shop','product-not-at-till']),
E('product-stock-control','Products','What is stock control?',
  ['what is stock control','how do i track stock','stop tracking stock for an item','stock quantity not changing','turn off stock tracking','make an item that is not counted in stock'],
  'inventory track quantity switch low threshold safety counted count service not tracked',
  `The **Stock control** switch (product form → Inventory) makes AUREUM count the item. When it is on, each sale lowers that shop's stock, and you can set a **Low stock alert threshold** and **Safety stock**. Receive stock with **Goods Received** and correct it with **Stock Adjustments**.`,
  ['alerts-low','grn-receive']),
E('product-not-at-till','Products','A product isn\'t showing at the till',
  ['product not showing at the till','cant find product at the pos','item missing on checkout','product not appearing for cashier','why cant i sell this item'],
  'missing hidden not visible till pos shop assignment search category',
  `Check:\n\n1. **Products → edit the product → Shops**: is it available in the shop the till is signed in to?\n2. The till is signed in to the right **shop**.\n3. Spelling/code in the search box, and the category filter is on **All**.\n4. Wait a few seconds for sync, or refresh the till.`,
  ['product-shops','sync-status']),

/* ============ STOCK ============ */
E('po-create','Stock','How do I create a purchase order?',
  ['how do i create a purchase order','order stock from a supplier','make a po','purchase order','how do i order goods'],
  'purchase order po supplier order buy stock lines unit cost pdf',
  `Open **Purchases** and press **New purchase order**: choose the supplier and shop, add product lines with **quantity** and **unit cost**, and save. Saved orders keep an exact copy of their lines and can be downloaded as a **PDF**. Use the date filter (default *All time*) to find old ones. When the goods arrive, record them in **Goods Received**.`,
  ['grn-receive','supplier-add'], { pages:['purchases'] }),
E('grn-receive','Stock','How do I receive stock (Goods Received)?',
  ['how do i receive stock','how do i record a delivery','goods received note','add stock when goods arrive','grn','receive goods from supplier'],
  'grn goods received delivery arrive stock in expiry quantity invoice supplier direct purchase order',
  `Open **Goods Received** and create a note — either **directly** or against a **purchase order**. For each line enter the **Quantity**, optional **Expiry date**, and **Unit cost**; add any additional costs. Saving **adds the quantities to that shop's stock immediately**. Saved notes open on screen and download as PDF.`,
  ['grn-edit','po-create'], { pages:['goods-received'] }),
E('grn-edit','Stock','Can I edit or delete a Goods Received note?',
  ['can i edit a grn','delete a goods received note','i made a mistake on a grn','wrong quantity on goods received','undo goods received','correct a received note'],
  'edit delete locked mistake wrong correct undo reverse completed',
  `No — a completed note is **locked** because it has already added stock. To fix a mistake, record a **Stock Adjustment** (Reduce, Add or Override) for that shop.`,
  ['stock-adjustment','grn-receive']),
E('stock-adjustment','Stock','How do I correct or count stock (Stock Adjustment)?',
  ['how do i adjust stock','stock count','how do i do a stocktake','reduce stock for damaged items','fix wrong stock quantity','override stock','stock take'],
  'adjustment add reduce override damage theft expired count correction reason shop',
  `Open **Stock Adjustments** and create one: choose the **shop**, the type — **Add**, **Reduce** or **Override** (set the quantity to an exact number) — pick a **reason**, and add the products. Use it for damage, theft, stock-takes and corrections. Every adjustment is kept in the list.`,
  ['alerts-negative','grn-edit'], { pages:['stock-adjustments'] }),
E('stock-transfer','Stock','How do I move stock between shops?',
  ['how do i transfer stock','move stock to another shop','transfer of goods','send items to my other store','shop to shop transfer'],
  'transfer move shop branch from to stock between',
  `Open **Transfer of Goods**, choose the **From shop** and **To shop**, add the products and quantities and save. Both shops' stock updates. Completed transfers are permanent records; to correct one, make a transfer back the other way.`,
  ['transfer-view','stock-per-shop'], { pages:['stock-transfers'] }),
E('transfer-view','Stock','How do I look at a saved transfer?',
  ['how do i view a saved transfer','see old transfers','transfer details','download transfer pdf','check what was transferred'],
  'view saved open details before after pdf history',
  `On **Transfer of Goods**, click the row (or **VIEW**) to open it on screen: the shops, date, each product's quantity and the stock **before → after** at both shops. **Download PDF** is inside it (or **PDF** in the list).`,
  ['stock-transfer']),
E('stock-per-shop','Stock','Is stock kept separately for each shop?',
  ['is stock separate for each shop','shared stock between shops','stock in each store','how does stock work with several shops','one stock for all shops'],
  'separate independent per shop branch location total',
  `Yes. Each shop has its **own stock** for every product. Sales, goods received, adjustments and transfers all affect the shop they are recorded for. **All Shops** views simply add the shops together.`,
  ['stock-transfer','product-shops']),
E('supplier-add','Stock','How do I add a supplier?',
  ['how do i add a supplier','add vendor','supplier list','where do i keep supplier details'],
  'supplier vendor phone email address notes',
  `Open **Suppliers → Add Supplier** and enter the name, phone, email, address and notes. You can also choose **+ Add new supplier…** from the supplier list inside a purchase order, Goods Received note or stock adjustment.`,
  ['po-create'], { pages:['suppliers'] }),

/* ============ PEOPLE ============ */
E('add-customer','People','How do I add a customer?',
  ['how do i add a customer','create customer','customer list','save customer details','add client'],
  'customer client phone email preferred shop notes import',
  `Open **Customers → Add Customer** and enter the full name, phone, optional email, preferred shop and notes. At the till you can attach a customer to a sale. **Import** and **Export** (CSV/Excel/PDF) are available.`,
  ['customer-segments','loyalty-points'], { pages:['customers'] }),
E('customer-segments','People','What are customer segments (New, Regular, VIP)?',
  ['what is a vip customer','customer segments','how are customers classified','what makes a customer regular','vip customers'],
  'vip regular new segment spent orders lifetime classify',
  `Segments are automatic: **VIP** = spent **$200 or more**, or **15 or more orders**; **Regular** = spent **$50 or more**, or **3 or more orders**; otherwise **New**.`,
  ['loyalty-points']),
E('loyalty-points','People','How do loyalty points work?',
  ['how do loyalty points work','can customers redeem points','loyalty programme','reward points','how do customers earn points'],
  'loyalty points rewards redeem earn spent',
  `Customers show **one loyalty point per dollar spent**. This is for information only — AUREUM does **not** let customers redeem points at the till.`,
  ['store-credit','not-available']),
E('store-credit','People','How does store credit work?',
  ['how does store credit work','add credit to a customer','customer credit balance','gift card','voucher balance','can customers pay with store credit'],
  'store credit balance gift card voucher adjust amount',
  `**Store credit** is a balance you adjust by hand in **Customers** (open the customer and adjust the amount). The till does not spend it automatically — a cashier can record a credit sale with the **Other** payment button and type "Store credit".`,
  ['payment-methods-till','loyalty-points']),
E('add-employee','People','How do I add an employee or cashier?',
  ['how do i add an employee','add a cashier','create staff member','new employee','how do i give a cashier a pin','how do i add a cashier to another shop'],
  'employee cashier staff worker role shop pin active new assign shop',
  `Open **Employees → Add Employee**: full name, **role**, **assigned shop**, phone, optional email and a **4-digit PIN** (needed to sign in at the till). Keep **Active** switched on. They can then sign in at the POS with their name and PIN.`,
  ['employee-pin','roles','employee-remove'], { pages:['employees'] }),
E('employee-pin','People','How do PINs work? How do I change one?',
  ['how do i change a cashiers pin','employee pin','pin must be 4 digits','cashier forgot pin','reset pin','pin not accepted','pin not working'],
  'pin code access four digits cashier forgot change reset incorrect problem wrong',
  `A PIN is **exactly 4 digits**. Change it in **Employees → open the employee → PIN / access code → Save employee**. You can switch off the PIN requirement for cashiers in **Settings → Users & Permissions → Requires PIN to sign in at the till** (managers and administrators always need one).`,
  ['permissions-settings','add-employee']),
E('employee-remove','People','How do I remove or disable an employee?',
  ['how do i remove an employee','disable a cashier','employee left the company','deactivate employee','delete staff member'],
  'remove delete deactivate disable left active switch',
  `Open the employee and switch **Active** off, then **Save employee** — they can no longer sign in at the till, and their past sales stay on record.`,
  ['add-employee']),
E('employee-hours','People','How do I record employee working hours?',
  ['how do i record hours worked','employee calendar','timesheet','staff hours','track working hours'],
  'hours calendar days worked timesheet month summary',
  `Open **Employees → Calendar**: pick a month, log the hours for each employee on each day, and see the **monthly summary** (days worked and total hours). The employee list can also be exported.`,
  ['add-employee'], { pages:['employees'] }),

/* ============ SALES & REPORTS ============ */
E('receipts-find','Sales & reports','How do I find a receipt?',
  ['how do i find a receipt','look up an old sale','search receipts','view a past sale','where are my sales','receipt history'],
  'receipt sale history list find search view detail filter date number',
  `Open **Receipts** in the Back Office: every sale and refund is listed with its items, total, payment, cashier and shop. Use the **date filter**, then click a receipt for the full breakdown (subtotal, discount, tax, tendered, change and any refunds). At the till, use **Today's Sales** for today's receipts.`,
  ['todays-sales','refund-how'], { pages:['sales'] }),
E('refund-how','Sales & reports','How do I refund a customer?',
  ['how do i refund','customer wants a refund','return an item','give money back','process a refund','refund one item from a sale'],
  'refund return item money back reverse receipt reason partial',
  `Refunds are done **item by item at the till**:\n\n1. Press **Today's Sales** and open the receipt.\n2. Press **Refund items…**.\n3. Choose the products and quantities, add a reason and confirm.\n\nTax and discount are refunded in proportion, exactly to the cent, and the refund shows on the receipt. Managers and administrators can always refund; cashiers only if **Can process refunds** is on in Settings.`,
  ['refund-who','refund-cant-find']),
E('refund-who','Sales & reports','Who can refund?',
  ['who can refund','cashier cannot refund','allow cashiers to refund','refund button missing','why is there no refund button'],
  'refund permission cashier manager button missing allow settings',
  `Managers and administrators can always refund. For cashiers, switch on **Settings → Users & Permissions → Can process refunds** and press **Save changes**. Also, the receipt must still have items left to refund.`,
  ['refund-how','permissions-settings']),
E('refund-cant-find','Sales & reports','Can I delete a receipt?',
  ['can i delete a receipt','remove a sale','cancel a sale','void a transaction','how do i void a sale','undo a sale'],
  'delete void cancel remove undo sale transaction receipt permanent',
  `Receipts are **permanent** — they can't be deleted or edited, which keeps your records honest. To reverse a sale use **Refund items…** on its receipt. To correct stock use a **Stock Adjustment**.`,
  ['refund-how','stock-adjustment']),
E('sales-by-product','Sales & reports','How do I see which products sell best?',
  ['how do i see my best selling products','sales by product','which items make the most profit','product sales report','top sellers'],
  'sales by product best selling profit revenue top performers ranking',
  `Open **Sales by Product** to see revenue and profit for each product over the dates and shop you choose. The Dashboard also shows your top performers.`,
  ['dashboard-overview'], { pages:['sales-by-product'] }),
E('accounting','Sales & reports','How does Accounting work?',
  ['how do i see my profit','income statement','profit and loss','how is profit calculated','accounting page','net income'],
  'accounting income statement profit loss revenue cogs gross expenses net',
  `**Accounting** shows an **Income Statement** for the dates you choose: revenue (sales less refunds), cost of goods sold (estimated from the cost of what was sold), gross profit, operating expenses and **net income**. Add your costs with **Add expense**.`,
  ['add-expense'], { pages:['accounting'] }),
E('add-expense','Sales & reports','How do I record an expense?',
  ['how do i add an expense','record rent','add a cost','track expenses','record salaries'],
  'expense rent utilities salaries cost category amount description',
  `On **Accounting** press **Add expense**: date, **category** (any words, like Rent or Salaries), description and amount. Expenses reduce net income on the Income Statement.`,
  ['accounting'], { pages:['accounting'] }),
E('reports-overview','Sales & reports','What reports are there?',
  ['what reports are there','where are the reports','inventory report','stock valuation','staff report','list of reports'],
  'reports inventory valuation summary low stock staff snapshot shifts',
  `**Reports** has six tabs: **Available Inventory**, **Inventory Valuation** (negative stock is not counted as an asset), **Inventory Summary**, **Low Stock**, **Staff Snapshot** and **Shifts**. Most lists have paging and **Export** (CSV, Excel, PDF).`,
  ['shifts-report','alerts-view-all'], { pages:['reports'] }),
E('shifts-report','Sales & reports','Where can I see shifts and cash differences?',
  ['where can i see shifts','shift report','who closed their shift','cash short or over','closed shifts list','see cash variance'],
  'shifts report open closed variance cashier cash difference flagged earlier day',
  `Open **Reports → Shifts**: **open shifts** (flagged if left from an earlier day, with net sales so far) and **closed shifts** (paged, date filter, click one for the detail) with the cashier and the cash **variance**. At the till, managers can open **Closed shifts** from the Shift panel.`,
  ['shift-close','shift-variance']),
E('export-data','Sales & reports','How do I export or print data?',
  ['how do i export data','download reports','export to excel','save as pdf','download receipts list'],
  'export download csv excel pdf print save list',
  `Look for the **Export** button above most lists and reports — choose **CSV, Excel or PDF**. It exports what is on screen (respecting your filters).`,
  ['product-export']),

/* ============ THE TILL ============ */
E('pos-signin','The till','How do I sign in at the till?',
  ['how do i sign in to the pos','cashier login','how do i log in at checkout','sign in at the till','start work at the till'],
  'sign in login shop name pin float start shift gate cashier',
  `At the POS: choose the **shop**, choose **your name**, type your **PIN**, and press **Start Shift** (or **Continue Shift** if you already have one open). If you have no open shift you can enter your **opening float**.`,
  ['shift-start','employee-pin']),
E('shift-start','Shifts','What is a shift and the opening float?',
  ['what is a shift','what is an opening float','how do i start a shift','what is float','start my shift','how do i set the opening cash'],
  'shift open start float cash drawer money in drawer begin opening cash starting balance',
  `A **shift** is your work period at a shop. The **opening float** is the cash already in your drawer when you start. **Every cashier has their own shift**, so each person's sales and cash are counted separately and never mixed. A shift stays open — even across days and devices — until it is closed.`,
  ['shift-close','shift-own']),
E('shift-own','Shifts','Do cashiers have separate shifts?',
  ['do cashiers have separate shifts','two cashiers same till','mix up cashiers money','each cashier own shift','shared till cash'],
  'separate own individual cashier money mixed second cashier signs in',
  `Yes. When a second cashier signs in they start **their own shift** with their own float, sales and cash to count; the first cashier's shift keeps running. Money from different cashiers is never mixed. Managers can see everyone's open shifts in the Shift panel.`,
  ['shift-start','shift-close']),
E('shift-close','Shifts','How do I close my shift?',
  ['how do i close my shift','end of day cash up','close the till','end my shift','count the cash drawer','cash up at the end of the day'],
  'close end shift cash up count drawer report finish day',
  `1. Press the **Shift** button (top bar).\n2. Press **Close my shift…**.\n3. Type the **counted cash** in the drawer. If it doesn't match the expected amount, add a note.\n4. Confirm — a printable **shift report** appears and you are signed out.\n\nExpected cash = opening float + cash sales − cash refunds. **Signing out alone does not close your shift.**`,
  ['shift-variance','shift-left-open','shift-who-closes']),
E('shift-variance','Shifts','My cash doesn\'t balance at shift close',
  ['cash doesnt balance','drawer is short','cash over','variance at close','counted cash does not match','why is expected cash different'],
  'balance variance short over difference counted expected mismatch note refunds',
  `The close screen compares **expected** cash (opening float + cash sales − cash refunds) with what you **counted**. Check: a recount; refunds paid from your drawer reduce the expected cash; Card/Mobile/Other sales are not cash. If a difference remains you must add a note, and it is recorded on the shift report and in **Reports → Shifts**.`,
  ['shift-close','shifts-report']),
E('shift-left-open','Shifts','A cashier left their shift open',
  ['cashier left shift open','shift from yesterday still open','how do i close someone elses shift','old shift not closed','forgot to close shift'],
  'left open yesterday not closed manager close other cashier earlier day',
  `A manager or administrator can close it: open the **Shift** panel and look under **Other cashiers' open shifts here**, press **Close…**, count the cash and confirm. Or the cashier can sign in and close their own shift. Shifts from an earlier day are flagged.`,
  ['shift-close','shift-who-closes']),
E('shift-who-closes','Shifts','Who can close a shift?',
  ['who can close a shift','can a cashier close their shift','manager close shift','permission to close shift'],
  'close permission cashier manager administrator own anyone',
  `A cashier can close **their own** shift. **Shop Managers and Administrators** can close anyone's shift and can open the **Closed shifts** list.`,
  ['shift-close']),
E('sell-basic','The till','How do I make a sale?',
  ['how do i make a sale','how do i sell','ring up a customer','how does checkout work','process a sale','how to use the till'],
  'sell sale checkout charge ticket add product pay cash receipt basic',
  `1. Tap products (or search by name, code or barcode) to add them to the **ticket**.\n2. Use **− / +** to change quantities.\n3. Optionally add a **Discount**, **Customer** or **Note**.\n4. Choose **Cash, Card, Mobile or Other**. For cash, type the amount received — the change is shown.\n5. Press **Charge** — the receipt appears.`,
  ['payment-methods-till','discount-till','receipt-print']),
E('till-search','The till','How do I find products quickly at the till?',
  ['how do i search for a product at the till','change page of products','swipe to next page','how many products per page','sort products at the till'],
  'search page paging swipe sort category filter products per page 12 24 48',
  `Use the **search box** (name, code or barcode) and the **category** buttons. Products are shown in pages of **12, 24 or 48** (your choice, remembered) and you can **swipe left/right** on a touch screen to change page. There is also a sort menu (A–Z, Category, quantity…).`,
  ['sell-basic','till-phone']),
E('discount-till','The till','How do I give a discount?',
  ['how do i give a discount','add discount to a sale','percentage discount','cashier cannot give discount','discount button missing','apply a discount'],
  'discount percent amount button missing permission cashier allow promo customer',
  `On the ticket press **+ Discount**, choose **Percent %** or **Amount**, enter the value and **Apply Discount**. The discount is shared across the lines. If the button is missing for a cashier, switch on **Settings → Users & Permissions → Can apply discounts**.`,
  ['permissions-settings','sell-basic']),
E('price-change-till','The till','How do I change an item\'s price during a sale?',
  ['how do i change the price at the till','cashier edit price','override price','sell at a different price','price change at checkout','cant change price at checkout'],
  'price change override edit till checkout permission tap ticket list price',
  `On the ticket, tap the item's **price**, type the new price and **Apply**. It changes **only that sale** — the product's own price stays the same and the receipt keeps the list price. Managers and administrators can always do this; for cashiers switch on **Settings → Users & Permissions → Can change an item's price at checkout**.`,
  ['permissions-settings','edit-product']),
E('customer-on-sale','The till','How do I add a customer or note to a sale?',
  ['how do i add a customer to a sale','attach customer to receipt','add a note to a sale','put customer name on receipt'],
  'customer note sale attach receipt name chip',
  `On the ticket press **Customer** to pick or add one, or **Note** to type a message. The customer's name and the note appear on the receipt.`,
  ['add-customer','sell-basic']),
E('payment-methods-till','The till','How do Card, Mobile and Other payments work?',
  ['does aureum take card payments','how do card payments work','mobile money payment','what is the other payment button','record a card payment','can i accept ecocash'],
  'card mobile money other cash payment method record process terminal ecocash voucher bank transfer',
  `**Cash** — enter the amount tendered; the change is shown. **Card** and **Mobile** only **record** which method the customer used — AUREUM does **not** process card or mobile payments. **Other** is for vouchers, bank transfer or store credit: type the payment type. Which buttons show is set in **Settings → Payment Methods**.`,
  ['payment-methods-settings','not-available']),
E('dual-currency','The till','Can I accept two currencies?',
  ['can i accept two currencies','second currency','dual currency','exchange rate','accept dollars and local currency'],
  'currency dual second exchange rate usd zwg zar euro',
  `Yes — in **Settings → Business Profile** switch on **dual currency**, choose the second currency and enter the **exchange rate**, then **Save changes**. The till can then show and take payment in the second currency.`,
  ['business-profile']),
E('receipt-print','The till','How do I print a receipt?',
  ['how do i print a receipt','print receipt','usb printer','bluetooth printer','thermal printer','receipt printer','how do i connect a printer'],
  'print receipt printer usb bluetooth thermal browser paper reprint connect setup pair',
  `After a sale the receipt shows **Print Receipt** (browser print), **Print via USB** (a USB thermal printer, Chrome/Edge on a computer) and **Print via Bluetooth** (a printer already paired to the device). To print an old receipt, open it from **Today's Sales**. To print automatically, see **Settings → Receipts**.`,
  ['printer-problems','receipt-auto-print','receipt-email']),
E('receipt-auto-print','The till','How do I print receipts automatically?',
  ['how do i print automatically','auto print receipt','print every sale automatically','receipt prints by itself'],
  'automatic auto print after sale switch settings receipts',
  `Switch on **Settings → Receipts → Print receipt automatically after sale** and **Save changes**. It uses a connected USB printer if there is one, otherwise the browser print window. Old receipts you open later are never printed automatically.`,
  ['receipt-print','receipts-settings']),
E('receipt-email','The till','Can I email a receipt?',
  ['how do i email a receipt','send receipt to customer','email receipt button','customer wants receipt by email'],
  'email receipt send customer mail button',
  `Switch on **Settings → Receipts → Show an "Email receipt" button on receipts**. Then press **Email receipt** on a receipt: it opens **your own email app** with the receipt written out (addressed to the customer when their email is saved). AUREUM does not send emails itself.`,
  ['receipts-settings','email-notifications']),
E('todays-sales','The till','What is Today\'s Sales?',
  ['what is todays sales','see todays sales at the till','todays total','reprint a receipt at the till','todays sales button missing'],
  'todays sales list day total circular arrow button open receipt cashier hidden permission',
  `The circular-arrow button in the till's top bar opens **Today's Sales**: today's sales for the current shop with the **day total**. Tap a row for the full receipt (and **Refund items…** if you may refund). If it's hidden for a cashier, switch on **Settings → Users & Permissions → Can view Today's Sales at the till**.`,
  ['refund-how','permissions-settings']),
E('till-tax','The till','How is tax calculated at the till?',
  ['how is tax calculated','change tax at the till','tax percent on ticket','prices include tax how it works','tax inclusive'],
  'tax rate percent inclusive exclusive added on top vat total',
  `The tax % is filled in from **Settings → Taxes** and can be changed on the ticket. If **Prices include tax** is on, the total stays the same and the tax is shown inside it; if off, tax is **added on top**. Only products with **Charge tax** switched on are taxed.`,
  ['taxes-settings','product-tax']),
E('till-phone','The till','How does the till work on a phone or tablet?',
  ['can i use the till on a phone','mobile layout','tablet checkout','view ticket button','till on small screen','use pos on ipad'],
  'phone tablet mobile small screen view ticket bar swipe ipad android layout',
  `On a phone the product list fills the screen and a **View ticket** bar at the bottom shows the item count and total; tap it to see the ticket and **Back to products** to return. On tablets the products and ticket sit side by side. Swipe left/right to change product pages.`,
  ['till-search','install-app']),
E('till-offline','The till','What happens to sales when the till is offline?',
  ['sell offline','till lost internet','will my offline sales be saved','offline sales sync','pos offline mode'],
  'offline sales saved device sync later connection lost',
  `The till keeps working. Sales are saved on the device and sent to your account automatically when the internet is back; receipt numbers continue in sequence. Keep the device on and don't clear the browser's data until it says **Synced**.`,
  ['offline','sync-status']),

/* ============ SETTINGS ============ */
E('settings-overview','Settings','What can I change in Settings?',
  ['what is in settings','where are the settings','list of settings','what can i configure'],
  'settings tabs options configure profile stores devices taxes receipts payment notifications permissions billing help',
  `**Settings** has ten tabs: **Business Profile**, **Stores**, **POS Devices**, **Taxes**, **Receipts**, **Payment Methods**, **Notifications**, **Users & Permissions**, **Billing & Subscription** and **Help & FAQ**. After changing a switch press **Save changes** — an "Unsaved changes" hint reminds you. Tills pick up changes within seconds.`,
  ['settings-not-saving'], { pages:['settings'] }),
E('business-profile','Settings','How do I change my business name or currency?',
  ['how do i change my business name','change currency','business email','business profile','set my currency'],
  'business name currency profile email dollar zar euro pound zwg',
  `**Settings → Business Profile**: business name, email and **currency**, plus the optional second currency. Press **Save changes**. The same tab has **Data recovery**.`,
  ['dual-currency','data-recovery'], { pages:['settings','settings-general'] }),
E('add-store','Settings','How do I add, rename or remove a shop?',
  ['how do i add a shop','add a new store','create another branch','rename a shop','remove a store','open a second location'],
  'shop store branch location add new rename remove stores second',
  `**Settings → Stores → Add store** (or type a name under *Add a new shop…* in the shop dropdown). During your free trial every shop is included. On a paid plan each shop is **$5/month**: you are shown the new monthly total and asked to confirm; your card is charged and **if the payment fails the shop is not added**. Use the pencil to rename and the **✕** to remove (this lowers your next invoice). A new shop starts with no products — assign products to it.`,
  ['add-shop-cost','product-shops'], { pages:['settings-stores'], pay:true, store:'Adding a shop changes your subscription, which is managed from your AUREUM account on the web. Use Settings → Stores to rename or remove shops.' }),
E('pos-devices','Settings','What are POS Devices?',
  ['what are pos devices','register a till','add a device','pos device list','tablet registration'],
  'pos devices terminals tablets mobile registered list record',
  `**Settings → POS Devices** is a list of your terminals, tablets and phones per store, kept for your records. Adding a device there does not limit where the POS can be used.`,
  ['open-pos']),
E('taxes-settings','Settings','How do I set up tax?',
  ['how do i set up tax','set vat rate','prices include tax setting','tax name','change the tax rate','tax settings','where do i enter the tax percentage'],
  'tax vat rate name inclusive exclusive default new products setup percent percentage enter',
  `**Settings → Taxes**: set the **tax name** and **default rate**, then choose **Prices include tax** (on: tax is inside your prices; off: added on top), and **Apply tax to all new products by default**. Press **Save changes**. To make a single product tax-free, edit it and switch off **Charge tax on this product**.`,
  ['product-tax','till-tax'], { pages:['settings-taxes'] }),
E('receipts-settings','Settings','How do I customise receipts (logo, header, footer)?',
  ['how do i add my logo to receipts','change receipt footer','receipt header message','customise receipt','put my business logo on the receipt','receipt text'],
  'receipt logo header footer message cashier name customise design thank you',
  `**Settings → Receipts**: type a **header** (under the business name) and **footer** message, upload your **logo** and keep **Show business logo on receipts** on. You can also control **Show cashier name on receipts**, **Print receipt automatically after sale** and **Show an "Email receipt" button on receipts**. Press **Save changes**.`,
  ['receipt-auto-print','receipt-email','receipt-no-logo'], { pages:['settings-receipts'] }),
E('payment-methods-settings','Settings','How do I choose which payment buttons show?',
  ['how do i hide card payments','turn off a payment method','which payment methods can cashiers use','disable mobile money','remove other payment button'],
  'payment methods cash card mobile other buttons hide show enable disable',
  `**Settings → Payment Methods**: switch **Cash**, **Card**, **Mobile money** and **Other** on or off, then **Save changes**. At least one must stay on. *Allow split payments* is marked **Coming soon**.`,
  ['payment-methods-till','split-payments'], { pages:['settings-payments'] }),
E('notifications-settings','Settings','What notifications are available?',
  ['what notifications are there','get alerts for new sales','refund alerts','shift alerts','notification settings','popup when a sale happens'],
  'notifications alerts popup new sale refund shift low stock daily summary',
  `**Settings → Notifications** (they appear while the Back Office is open): **Low stock alerts**, **Daily sales summary**, **New sale notifications**, **Refund alerts** and **Shift opened / closed alerts**. There are no emails or phone push notifications.`,
  ['email-notifications','daily-summary'], { pages:['settings-notifications'] }),
E('permissions-settings','Settings','How do I control what cashiers can do?',
  ['how do i limit what cashiers can do','cashier permissions','restrict cashiers','what can cashiers do','user permissions','stop cashiers giving discounts'],
  'permissions cashier restrict allow discount refund reports price pin users',
  `**Settings → Users & Permissions** has switches for cashiers: **Can apply discounts**, **Can process refunds**, **Can view Today's Sales at the till**, **Can change an item's price at checkout** and **Requires PIN to sign in at the till**. Managers and administrators can always do all of these. Press **Save changes**.`,
  ['roles','discount-till','refund-who'], { pages:['settings-users'] }),
E('settings-not-saving','Settings','My settings don\'t seem to save',
  ['settings not saving','switch wont stay','my change didnt work','i turned it on but nothing happened','save changes button','settings reset'],
  'save unsaved switch toggle change not working stay reset hint',
  `Changes only take effect after you press **Save changes** at the bottom of that settings tab (an **Unsaved changes — press Save** hint shows until you do). Tills pick up saved changes within a few seconds; if one doesn't, refresh it.`,
  ['settings-overview','refresh-old']),
E('data-recovery','Settings','How do I recover missing records?',
  ['how do i recover missing records','data recovery','my records disappeared','restore lost data','purchase orders missing','expenses disappeared','i lost my data'],
  'recovery restore missing lost disappeared records device cache check',
  `Try **Settings → Business Profile → Data recovery → Check this device** on the device where you last saw the records, then **Restore**. If they are still missing, send a **ticket** and say roughly when you last saw them — the AUREUM team keeps safety copies and can look.`,
  ['missing-data'], { human:true }),

/* ============ BILLING ============ */
E('price','Billing','How much does AUREUM cost?',
  ['how much does aureum cost','what is the price','subscription price','how much per shop','monthly fee','pricing'],
  'cost price monthly fee subscription per shop five dollars $5 charge',
  `AUREUM costs **$5 per shop, per month**, paid by card (Stripe). For example 3 shops = $15/month. Every shop is included during the **14-day free trial**.`,
  ['free-trial','subscribe'], { pay:true, store:STORE }),
E('free-trial','Billing','How long is the free trial?',
  ['how long is the free trial','trial period','when does my trial end','can i extend my trial','free trial days'],
  'free trial 14 days end extend expires',
  `The free trial is **14 days** and includes every shop. **Settings → Billing & Subscription** shows when it ends. Need more time? Send a **ticket** and the AUREUM team can extend it.`,
  ['subscribe','price'], { human:true, pay:true, store:STORE }),
E('subscribe','Billing','How do I subscribe?',
  ['how do i subscribe','how do i pay for aureum','pay my subscription','start paying','subscribe with card'],
  'subscribe subscription pay card stripe billing owner button',
  `The **owner** opens **Settings → Billing & Subscription** and presses **Subscribe with card — $X/month (N shops × $5)**, then pays on Stripe's own page. Your card details are never stored by AUREUM.`,
  ['price','add-shop-cost'], { pay:true, store:STORE, pages:['settings-billing'] }),
E('add-shop-cost','Billing','What does adding a shop cost?',
  ['what does an extra shop cost','how much to add a shop','pay for a new shop','do i pay more for another shop','additional shop price'],
  'extra additional shop cost charge five dollars prorated confirm declined second another',
  `On a paid plan each extra shop adds **$5 a month**. When you add one you see the new monthly total (e.g. $10 → $15) and confirm; your card is charged a prorated amount straight away. **If the payment fails the shop is not added.** During the free trial every shop is free.`,
  ['add-store','remove-shop-billing'], { pay:true, store:STORE }),
E('remove-shop-billing','Billing','What happens to my bill if I remove a shop?',
  ['what happens to my bill if i remove a shop','delete a shop billing','reduce subscription','cancel one shop','lower my bill'],
  'remove delete shop bill invoice lower reduce refund next',
  `Your **next invoice drops by $5** per removed shop. There is no refund for the month already paid. The change is applied automatically a few seconds after you remove the shop.`,
  ['add-shop-cost'], { pay:true, store:STORE }),
E('change-card','Billing','How do I change my card or cancel?',
  ['how do i change my card','update payment method','cancel my subscription','stop my subscription','manage card on stripe'],
  'card change update cancel stop stripe portal payment method',
  `As the owner, open **Settings → Billing & Subscription** and press **Manage card on Stripe**. There you can update your card or cancel. After cancelling you keep access until the period you paid for ends.`,
  ['payment-failed'], { pay:true, store:STORE }),
E('payment-failed','Billing','My payment failed / status says Past due',
  ['my payment failed','past due','card declined','why is my account past due','subscription payment problem'],
  'payment failed past due declined card problem retry fix',
  `A failed payment makes the status **Past due**. Open **Settings → Billing & Subscription → Manage card on Stripe** and update or retry your card. While past due you can't add shops. If it keeps failing after you've fixed the card, send a **ticket**.`,
  ['change-card','locked-out'], { human:true, pay:true, store:STORE }),
E('locked-out','Billing','The app is locked / says my subscription ended',
  ['app is locked','subscription has ended','i cant access my account because of billing','trial has ended locked out','grace period','my trial ended and i cant get in'],
  'locked lock out ended expired grace period suspended trial blocked access',
  `After a trial or paid period ends there is a **3-day grace period**, then the app is locked until the subscription is paid. The lock screen has a **Subscribe with card** button for the owner. A **Suspended** account can only be reactivated by the AUREUM team — send a ticket from another device or contact them.`,
  ['subscribe','payment-failed'], { human:true, pay:true, store:STORE }),
E('paynow','Billing','Can I pay with Paynow, EcoCash or cash?',
  ['can i pay with paynow','pay with ecocash','pay my subscription with mobile money','other ways to pay for aureum','pay by bank transfer'],
  'paynow ecocash onemoney innbucks mobile money bank transfer alternative payment subscription',
  `Subscriptions are paid **by card through Stripe only**. **Paynow is no longer accepted** for subscriptions; if you were already paid up on Paynow you keep access until your period ends, then please subscribe by card. (Paynow/EcoCash can still be recorded as a sale payment at the till using **Other**.)`,
  ['subscribe'], { pay:true, store:STORE }),
E('plan-update','Billing','It says my subscription covers fewer shops than I have',
  ['subscription covers fewer shops','update subscription to cover all shops','old subscription flat five dollars','why does it say update subscription','shops not covered'],
  'covers fewer shops update flat five grandfathered older subscription',
  `Older subscriptions started as a flat $5 and cover **1 shop**. Everything keeps working, but billing shows **Update subscription to cover all N shops — $X/month**. Pressing it charges the prorated difference once. You can't add further shops until your plan covers them.`,
  ['add-shop-cost'], { pay:true, store:STORE }),
E('payment-history','Billing','Where are my invoices and payment history?',
  ['where are my invoices','payment history','receipt for my subscription','download invoice','billing history'],
  'invoice payment history receipts billing statements export',
  `**Settings → Billing & Subscription → Payment history** lists every payment (date, method, period, amount, status) with **Export**. Stripe also emails receipts to the owner's email address.`,
  ['subscribe'], { pay:true, store:STORE }),
E('billing-dispute','Billing','I was charged twice / I want a refund of my subscription',
  ['i was charged twice','refund my subscription','wrong amount charged','dispute a charge','unauthorised charge','money taken from my card'],
  'charged twice double refund dispute wrong amount unauthorised overcharged chargeback subscription',
  `I can't see or change payments, and refunds or disputes need the AUREUM team. Please send a **ticket** with the date, the amount and the last 4 digits of the card (never the full number). The team will check and reply inside the ticket.`,
  ['payment-history','contact-support'], { human:true, pay:true, store:'Billing questions are handled by the AUREUM team — please send a ticket.' }),

/* ============ HELP & SUPPORT ============ */
E('contact-support','Help & support','How do I contact support?',
  ['how do i contact support','how do i send a ticket','talk to a person','report a problem','get help from the aureum team','submit a ticket'],
  'contact support ticket help team message report problem human person',
  `Open **Settings → Help & FAQ → My tickets → New ticket** (or press **Not solved? Contact support** under this chat). Write a short subject, choose a category and how urgent it is, describe what happened and tick **Include my chat with AUREUM Bot** so the team sees what was tried. The team replies **inside the ticket**.`,
  ['ticket-replies','feature-request'], { human:true, pages:['settings-help'] }),
E('ticket-replies','Help & support','Where do I see the team\'s reply to my ticket?',
  ['where is the reply to my ticket','how do i know if support replied','ticket status','red dot on help','check my tickets'],
  'ticket reply status red dot waiting solved reopen answer notification',
  `Open **Settings → Help & FAQ → My tickets**. A **red dot** on the **Help & support** button shows a new reply. A ticket shows **Waiting for AUREUM**, **Waiting for you**, **Solved** or **Closed**. You can write back, mark it **solved**, and writing to a solved ticket reopens it. There is no email notification.`,
  ['contact-support']),
E('feature-request','Help & support','Can I suggest a new feature?',
  ['can i suggest a feature','feature request','i wish aureum could','request an improvement','missing feature'],
  'suggest request feature idea improvement wish wishlist missing',
  `Yes please. Send a **ticket** and choose the category **Feature request**. Describe what you need and why — the team reads every one.`,
  ['contact-support'], { human:true }),

/* ============ TROUBLESHOOTING ============ */
E('cant-sign-in','Troubleshooting','I can\'t sign in',
  ['i cant sign in','login not working','wrong password','cannot log in','sign in failed','account not found'],
  'sign in login problem password email wrong cannot access account owner staff pin',
  `- **Owner:** check the email and password (use **Forgot password**; the eye icon shows what you type).\n- **Cashier:** staff sign in only at the **POS** with their name and PIN — not in the Back Office.\n- **"Can't load data" / locked screen:** see the billing and sync answers.\nStill stuck? Send a ticket.`,
  ['forgot-password','who-can-sign-in','locked-out'], { human:true }),
E('sync-problem','Troubleshooting','The app shows a sync problem or can\'t load data',
  ['sync problem','cant load data','data wont load','sync error message','changes not saving to the cloud','stuck syncing'],
  'sync problem error cant load retry stuck internet connection saving',
  `Check the internet, then refresh once (**Ctrl+Shift+R**). If it says **Can't load data**, press retry — nothing is lost. Saving is protected: AUREUM refuses saves that would delete data. If the message stays, send a **ticket** and include what it says.`,
  ['sync-status','refresh-old'], { human:true }),
E('missing-data','Troubleshooting','Some of my records are missing',
  ['records are missing','data disappeared','sales missing','products vanished','lost purchase orders','where did my data go','where did my products go'],
  'missing lost disappeared vanished deleted records sales products data gone',
  `First try **Settings → Business Profile → Data recovery → Check this device** on the device where you last saw them. Make sure date filters aren't hiding them (lists default to *All time*, the Dashboard to *Today*). If they are still gone, send a **ticket** with roughly when you last saw them — AUREUM keeps rolling safety copies the team can check.`,
  ['data-recovery','contact-support'], { human:true }),
E('printer-problems','Troubleshooting','My printer isn\'t printing',
  ['printer not working','receipt not printing','usb printer not found','bluetooth printer wont connect','printing problem','printer does nothing'],
  'printer printing problem usb bluetooth thermal paper connect pair not working chrome edge',
  `- **USB printing** needs **Chrome or Edge on a computer** with the printer connected.\n- **Bluetooth** needs the printer **paired** to the device first.\n- Otherwise use **Print Receipt** (browser print) and pick your printer.\n- Check paper, power and that the right printer is selected. A USB printer must be allowed when the browser asks.`,
  ['receipt-print']),
E('stock-wrong','Troubleshooting','The stock numbers look wrong',
  ['stock looks wrong','stock numbers are incorrect','quantity doesnt match','why did my stock change','stock went down by itself'],
  'stock wrong incorrect quantity mismatch changed unexpected count',
  `Stock is kept **per shop**. Check what changed it: **Goods Received**, **Stock Adjustments**, **Transfer of Goods**, sales and refunds. Negative stock means more was sold than recorded. Fix with a **Stock Adjustment → Override** to the counted number.`,
  ['stock-adjustment','alerts-negative','stock-per-shop']),
E('tax-wrong','Troubleshooting','The tax on my receipts looks wrong',
  ['tax is wrong','tax looks wrong on receipt','wrong vat amount','tax not charged','tax charged twice'],
  'tax wrong incorrect vat amount receipt inclusive exclusive product charge',
  `Check three things: the **rate** and **Prices include tax** in **Settings → Taxes**; whether each product has **Charge tax on this product** switched on; and any **discount** (it is shared across lines). With *Prices include tax* **on**, the total doesn't change — the tax is shown inside it.`,
  ['taxes-settings','product-tax','till-tax']),
E('receipt-no-logo','Troubleshooting','My logo, footer or cashier name isn\'t on the receipt',
  ['logo not showing on receipt','footer not printing','cashier name missing on receipt','receipt header not showing','receipt looks plain'],
  'logo footer header cashier name missing receipt not showing printing',
  `Open **Settings → Receipts**, upload the logo and make sure **Show business logo on receipts** / **Show cashier name on receipts** are on, type your header/footer, and press **Save changes**. The thermal printer prints the text lines (header, footer, cashier) but not the logo image.`,
  ['receipts-settings']),
E('cashier-missing-button','Troubleshooting','A cashier can\'t see a button (discount, refund, Today\'s Sales, price)',
  ['cashier cant see a button','button missing for cashier','cashier cannot refund or discount','feature missing at the till for staff','why cant my cashier'],
  'cashier missing button hidden permission discount refund todays sales price pin restricted',
  `These are controlled in **Settings → Users & Permissions**: **Can apply discounts**, **Can process refunds**, **Can view Today's Sales at the till**, **Can change an item's price at checkout**. Switch on what you want and **Save changes** — the till updates within seconds. Managers and administrators always have them.`,
  ['permissions-settings','roles']),

/* ============ NOT AVAILABLE ============ */
E('split-payments','Not available','Can a customer pay with two methods (split payment)?',
  ['can a customer split payment','pay half cash half card','split payments','two payment methods in one sale','pay part in cash part by card'],
  'split payment two methods half cash card combine multiple',
  `Not yet — **split payments are marked "Coming soon"**. Each sale is paid with **one** method. A workaround is to ring two separate sales.`,
  ['payment-methods-till','not-available']),
E('email-notifications','Not available','Does AUREUM send emails or text messages?',
  ['does aureum send emails','email me daily reports','sms alerts','whatsapp notifications','push notifications on my phone','get a text when a sale happens'],
  'email sms text whatsapp push notification send alert phone report scheduled',
  `No. AUREUM doesn't send emails, text messages or phone push notifications. **Alerts and the daily summary appear inside the Back Office** while it is open. **Email receipt** opens *your own* email app.`,
  ['notifications-settings','receipt-email','not-available']),
E('not-available','Not available','What can\'t AUREUM do?',
  ['what cant aureum do','limitations','features not available','does aureum have an online shop','can aureum do loyalty redemption','missing features'],
  'cannot limits unavailable not supported missing online shop ecommerce delivery integration redeem multiple tax rates',
  `Things AUREUM does **not** do (yet):\n\n- Split payments (coming soon) and card/mobile payment **processing** — Card/Mobile only record the method.\n- Redeeming loyalty points or automatic store-credit payments.\n- Sending emails, SMS or phone push notifications.\n- Different tax rates per product (one business rate; each product is taxed or not).\n- Editing or deleting completed receipts, Goods Received notes or transfers.\n- Separate Back Office logins for staff.\n\nWant one? Send a **Feature request** ticket.`,
  ['feature-request','split-payments']),
E('multiple-tax','Not available','Can different products have different tax rates?',
  ['can i have different tax rates','two tax rates','zero rated and standard rated','different vat for different products','multiple taxes'],
  'multiple different tax rates vat per product',
  `There is **one tax rate** for the business. Each product is simply **taxed or tax-free** (**Charge tax on this product**). Different rates per product aren't available — send a **Feature request** if you need them.`,
  ['product-tax','feature-request']),
E('staff-backoffice','Not available','Can my staff have their own Back Office login?',
  ['can staff log in to the back office','manager login for back office','give my manager access to reports','second user for the back office','share the owner account'],
  'staff manager back office login access user account share second',
  `Not at the moment: the **owner's** sign-in is used for the Back Office. Staff use their **name and PIN at the till** only. Managers get extra abilities at the till (refunds, closing shifts, Today's Sales) but not a Back Office login. Send a **Feature request** if you need it.`,
  ['who-can-sign-in','feature-request'])
];
const TOPICS = ['Getting started','Dashboard','Products','Stock','People','Sales & reports','The till','Shifts','Settings','Billing','Troubleshooting','Help & support','Not available'];
const POPULAR = ['add-product','product-import','shift-close','refund-how','alerts-negative','price','contact-support'];
const api = { KB, TOPICS, POPULAR };
if(typeof module !== 'undefined' && module.exports) module.exports = api; else root.AUREUM_KB = api;
})(typeof window !== 'undefined' ? window : globalThis);
