// Copies the AUREUM Bot (help-bot/kb.js = the help library, help-bot/engine.js = the search engine) into backoffice.html,
// between the markers below. Run after editing either file:   node tools/build-bot.mjs
import fs from 'node:fs';
const root = new URL('../', import.meta.url);
const read = f => fs.readFileSync(new URL(f, root), 'utf8').trimEnd();
const START = '/* ==== AUREUM HELP BOT (generated by tools/build-bot.mjs from help-bot/kb.js + help-bot/engine.js) ==== */';
const END = '/* ==== END AUREUM HELP BOT ==== */';
const block = '<script>\n' + START + '\n' + read('help-bot/kb.js') + '\n' + read('help-bot/engine.js') + '\n' + END + '\n</script>';
const file = new URL('backoffice.html', root); let html = fs.readFileSync(file, 'utf8');
const a = html.indexOf('<script>\n' + START);
if(a >= 0){ const b = html.indexOf(END, a); html = html.slice(0, a) + block + html.slice(b + END.length + '\n</script>'.length); }
else { const i = html.lastIndexOf('</body>'); html = html.slice(0, i) + block + '\n' + html.slice(i); }
fs.writeFileSync(file, html);
console.log('AUREUM Bot copied into backoffice.html (' + Math.round(block.length / 1024) + ' KB)');
